### PR TITLE
fix image in CSS prefix issue and ng-src prefix issue

### PR DESCRIPTION
**Pull request by vokidya**
- If the URL has not been wrapped in ' or " in css files, the prefix will not be added successfully.
image
**How to verify?**
Update the CSS [in Admin](http://premium.lvh.me:8080/admin/plugins/premium/settings), and then to check the [CSS file](http://premium.lvh.me:8080/jobs/public/premium/css/premium_custom_styles.css).

- If the HTML is load in JavaScript, the HTML tags will not be add the prefix.
image
**How to Verify?**
You will see the Image issue when you open [Profile Edit Page](http://10.63.88.62:8000/jobs/en-US/profile/view). 

- `ng-src` will not be add the prefix successfully.
image
**How to Verify?**
This issue happens on Apply Finish Page.

### CODE REVIEW

**Review by cecilliaQin — APPROVED** [review]
verified locally
image
image
image

**Comment by cecilliaQin** [comment]
fix the issue of prfix contains '/': verified locally, search and apply worked as expected.

**Review by JoseDomingoMoraNunezCB — COMMENTED** [review]
@shenghua-cb remember to make use of card https://careerbuilder.atlassian.net/browse/TN-1163 to document the PRs created cc @bradleylowenstein

**Review by JoseDomingoMoraNunezCB — COMMENTED** [review]
@shenghua-cb  @cecilliaQin  Just for clarification, prefix value should be defined without slashes at the beginning or the end. There are other places in the code that depend on this value.

On Friday, I tested the case of a prefix that is actually two in one: careers/jobs-search  and it seemed to work OK. Please keep this case in mind for any change cc @bradleylowenstein

**Review by JoseDomingoMoraNunezCB — APPROVED** [review]

**Pull request merged**
